name: Analysis Football Schedule

on:
  schedule:
    # 9:00 AM Myanmar Time (MMT)
    - cron: "30 2 * * *"

    # 6:00 PM Myanmar Time (MMT)
    - cron: "30 11 * * *"

  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Football Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: python bot.py
